name: Release

on:
    release:
        types:
            - published

jobs:
    build:
        name: Build and Upload Release Asset
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Install Rust toolchain
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            # Build the project
            - name: Build
              run: cargo build --release --target x86_64-unknown-linux-gnu

            # Ensure output directory exists
            - name: Prepare output directory
              run: mkdir -p dist

            # Copy binary to output directory
            - name: Copy binary to dist
              run: cp target/x86_64-unknown-linux-gnu/release/flohole dist/flohole-linux-x86_64

            # Verify dist directory contents
            - name: Verify dist directory
              run: ls -l dist

            # Upload artifact to the release
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: dist/flohole-linux-x86_64
                  asset_name: flohole-linux-x86_64
                  asset_content_type: application/octet-stream
